/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "9921b9f",
  "hashFull": "9921b9f9630e49dcc2a670683e96fecc1f78aa66",
  "date": "2026-08-19 19:55:50 -0400",
  "subject": "QA: 2026-08-19 Ticketer doesn't have have attachment management (pass 5)",
  "source": "git"
};
