/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "06b8eba",
  "hashFull": "06b8eba7d3d64f7c6b7308fcbaeea33f03d43dd0",
  "date": "2026-10-08 12:13:18 -0400",
  "subject": "Share Cloud Run nowMs as the splash clock; restore one-shot fade cues",
  "source": "git"
};
