/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "1f917c6",
  "hashFull": "1f917c6e654c41980a85fd9795cf6dd6c3c9f96d",
  "date": "2026-08-19 16:44:58 -0400",
  "subject": "QA: 2026-08-19 Tooltips should appear as stack, centered in mini-display, and get a shroud (pass 4)",
  "source": "git"
};
